[0m11:22:04.610291 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BA03EFA810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BA037F79E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BA7DCF6630>]}


============================== 11:22:04.610291 | 0bf3d462-9e78-4d36-89ec-6813e16b5363 ==============================
[0m11:22:04.610291 [info ] [MainThread]: Running with dbt=1.10.1
[0m11:22:04.610291 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Predator\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m11:22:16.832190 [debug] [MainThread]: Starter project path: C:\Users\Predator\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m11:22:16.843706 [info ] [MainThread]: 
Your new dbt project "datavault_postgres_test" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:22:16.843706 [info ] [MainThread]: Setting up your profile.
[0m11:22:16.848092 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m11:22:16.848092 [debug] [MainThread]: Command `dbt init` failed at 11:22:16.848092 after 12.36 seconds
[0m11:22:16.848092 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BA037F79E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BA01343CB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BA03D8BCE0>]}
[0m11:22:16.848092 [debug] [MainThread]: Flushing usage events
[0m11:22:17.777157 [debug] [MainThread]: An error was encountered while trying to flush usage events
